version: '3'

services:
  server:
    container_name: 'base-server'
    build: .
    depends_on:
      - postgres
      - redis
    ports:
      - '4000:4000'
    networks:
      - backend

  postgres:
    restart: always
    image: postgres:12
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: base
    ports:
      - '8080:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - backend

  redis:
    restart: always
    image: redis:6
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
      - '9090:6379'
    command: ['redis-server', '--bind', 'redis', '--port', '6379']
    volumes:
      - redis-data:/var/lib/redis/data
    networks:
      - backend

networks:
  backend:

volumes:
  postgres-data:
  redis-data:
